/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as EnhancementRouteImport } from './routes/enhancement'
import { Route as CraftingRouteImport } from './routes/crafting'
import { Route as ClassRouteImport } from './routes/class'
import { Route as CharacterRouteImport } from './routes/character'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardArtifactsMatchingIdRouteImport } from './routes/leaderboard.artifacts.$matchingId'

const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const EnhancementRoute = EnhancementRouteImport.update({
  id: '/enhancement',
  path: '/enhancement',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftingRoute = CraftingRouteImport.update({
  id: '/crafting',
  path: '/crafting',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassRoute = ClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterRoute = CharacterRouteImport.update({
  id: '/character',
  path: '/character',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardArtifactsMatchingIdRoute =
  LeaderboardArtifactsMatchingIdRouteImport.update({
    id: '/artifacts/$matchingId',
    path: '/artifacts/$matchingId',
    getParentRoute: () => LeaderboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/class': typeof ClassRoute
  '/crafting': typeof CraftingRoute
  '/enhancement': typeof EnhancementRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/leaderboard/artifacts/$matchingId': typeof LeaderboardArtifactsMatchingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/class': typeof ClassRoute
  '/crafting': typeof CraftingRoute
  '/enhancement': typeof EnhancementRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/leaderboard/artifacts/$matchingId': typeof LeaderboardArtifactsMatchingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character': typeof CharacterRoute
  '/class': typeof ClassRoute
  '/crafting': typeof CraftingRoute
  '/enhancement': typeof EnhancementRoute
  '/forum': typeof ForumRoute
  '/leaderboard': typeof LeaderboardRouteWithChildren
  '/leaderboard/artifacts/$matchingId': typeof LeaderboardArtifactsMatchingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/character'
    | '/class'
    | '/crafting'
    | '/enhancement'
    | '/forum'
    | '/leaderboard'
    | '/leaderboard/artifacts/$matchingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/character'
    | '/class'
    | '/crafting'
    | '/enhancement'
    | '/forum'
    | '/leaderboard'
    | '/leaderboard/artifacts/$matchingId'
  id:
    | '__root__'
    | '/'
    | '/character'
    | '/class'
    | '/crafting'
    | '/enhancement'
    | '/forum'
    | '/leaderboard'
    | '/leaderboard/artifacts/$matchingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterRoute: typeof CharacterRoute
  ClassRoute: typeof ClassRoute
  CraftingRoute: typeof CraftingRoute
  EnhancementRoute: typeof EnhancementRoute
  ForumRoute: typeof ForumRoute
  LeaderboardRoute: typeof LeaderboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enhancement': {
      id: '/enhancement'
      path: '/enhancement'
      fullPath: '/enhancement'
      preLoaderRoute: typeof EnhancementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crafting': {
      id: '/crafting'
      path: '/crafting'
      fullPath: '/crafting'
      preLoaderRoute: typeof CraftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class': {
      id: '/class'
      path: '/class'
      fullPath: '/class'
      preLoaderRoute: typeof ClassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character': {
      id: '/character'
      path: '/character'
      fullPath: '/character'
      preLoaderRoute: typeof CharacterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/artifacts/$matchingId': {
      id: '/leaderboard/artifacts/$matchingId'
      path: '/artifacts/$matchingId'
      fullPath: '/leaderboard/artifacts/$matchingId'
      preLoaderRoute: typeof LeaderboardArtifactsMatchingIdRouteImport
      parentRoute: typeof LeaderboardRoute
    }
  }
}

interface LeaderboardRouteChildren {
  LeaderboardArtifactsMatchingIdRoute: typeof LeaderboardArtifactsMatchingIdRoute
}

const LeaderboardRouteChildren: LeaderboardRouteChildren = {
  LeaderboardArtifactsMatchingIdRoute: LeaderboardArtifactsMatchingIdRoute,
}

const LeaderboardRouteWithChildren = LeaderboardRoute._addFileChildren(
  LeaderboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterRoute: CharacterRoute,
  ClassRoute: ClassRoute,
  CraftingRoute: CraftingRoute,
  EnhancementRoute: EnhancementRoute,
  ForumRoute: ForumRoute,
  LeaderboardRoute: LeaderboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
